### ISSUE TITLE
Galeb router should explain errors

### ISSUE THREAD

**Issue by stockrt** [globocom/galeb#4]
Galeb router should explain errors with and additional HTTP response header. This header should be appended to the response when Galeb router catches errors like the following (but not restricted to):
- No virtualhost was found in configuration
  For this type of error it would be nice to differentiate between 404 delivered from backend servers (due to lack of content, for sure) and 404 errors delivered by the Galeb itself due to lack of configuration for a given virtualhost.
- No backend available
  Also in this type of error it would be nice to know if the 503 came from the backend servers and it's hypothetical upstreams or if the 503 came from the Galeb itself due to the absence of available backends to serve the selected virtualhost and rule.
- Other errors catched by some internal condition or validation by the Galeb router
  The main idea is to differentiate errors delivered by the backend from errors delivered by the Galeb itself.

This additional header could be called 'Galeb-Explain' and delivered like the following example:

```
Galeb-Explain: virtualhost not found
Galeb-Explain: no backend available
```

This header will help in troubleshooting process, making it easier to tell where is the error coming from. If it is something with the backend application, then deliver the headers unchanged, but if it is some condition or internal validation within the Galeb router, it should be explained to the site administrator via the proposed header.

**Comment by tuxmonteiro** [comment]
![agreed](https://cloud.githubusercontent.com/assets/1256162/8596313/b00ae024-2624-11e5-85d7-b50c29e7a586.jpg)

**Comment by tuxmonteiro** [comment]
@stockrt See galeb-next: github.com/galeb/galeb-next

**Comment by tuxmonteiro** [comment]
@stockrt  Galeb-Next has X-Galeb-Error header. See io.galeb.router.ResponseCodeOnError.java
