### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by slok** [globocom/galeb#6]
[Prometheus](http://prometheus.io) is one of the new metrics/monitoring/alerting system, has been developed by Soundcloud. This system has gained a lot of traction and popularity, and it's being used in some of the big companies like Google, Soundcloud, DigitalOcean...

The community is growing and it supports a lot of [languages](http://prometheus.io/docs/instrumenting/clientlibs/) for its metric client including [Java](https://github.com/prometheus/client_java)

Would be nice to add support for prometheus along with statsD on the Galeb metrics.

**Comment by tuxmonteiro** [comment]
@slok tks.
Reopen that issue in github.com/galeb/galeb-next. Plz.
